### ISSUE TITLE
[Rule Tuning] Local Service Commands

### ISSUE THREAD

**Issue by bm11100** [elastic/detection-rules#1000] opened 2021-03-08 15:27 UTC
## Description
As is, the `Local Service Commands` rule is too noisy. It can be further refined to eliminate noise. 

## Original Rule
```
event.category:process and event.type:(start or process_started) and process.name:sc.exe and process.args:(config or create or failure or start)
```

## Potential Update

```
process where event.type == "start" and
  (process.name : "sc.exe" or process.pe.original_file_name : "sc.exe") and
  process.parent.name : ("cmd.exe", "wscript.exe", "rundll32.exe", "regsvr32.exe",
    "wmic.exe", "mshta.exe","powershell.exe", "pwsh.exe") and
  process.args:("config", "create", "start") and
  /* exclude SYSTEM SID - look for service creations by non-SYSTEM user */
  not user.id : "S-1-5-18"
```

**Comment by rw-access** [comment] 2021-03-08 15:34
Potential duplicate of  https://github.com/elastic/detection-rules/issues/47. We can fold https://github.com/elastic/detection-rules/issues/47 into this issue.

**Comment by bm11100** [comment] 2021-03-08 15:46
Good point, yeah there's definitely multiple options we could take with `sc`. We do also have `Service Command Lateral Movement` that we converted. I think we could close #47 and make note of your suggestions here.

**Comment by bm11100** [comment] 2021-03-08 17:03
Other recommendations in #47 by @rw-access 
* **Service Escalation with sc.exe**: look for user.name != "system"
* **Service Modification**: look for `binPath` or the other known fields in the command line, confirm that `\\` isn't in it
* **Remove Service Execution**: look for an arg starting with double backslashes `\\` and `start`
* **Remove Service Creation or Modification**: look for an arg starting with double backslashes `\\` and one of the other `non-start` commands that's already in our list

**Closed** 2021-04-13 16:31 UTC
Labels: OS: Windows, Rule: Tuning, v7.13.0
