### ISSUE TITLE
[FR] Update detection rule

### ISSUE THREAD

**Issue by Zawadidone** [elastic/detection-rules#1302] opened 2021-06-22 13:33 UTC
**Is your feature request related to a problem? Please describe.**
As far as I know after uploading detection rules using this tool it is not possible to edit/update rules without deleting the rules.

**Describe the solution you'd like**
Is it possible to create a new feature or integrate it in the upload-rule function, to update rules.
```bash
kibana upload-rule --rule-file <rule.tom> # upload rule
kibana <upload-rule/update-rule> --rule-file <rule.tom># day later update/edit rule
```

**Comment by rw-access** [comment] 2021-06-22 14:08
This might be a duplicate of #362

**Comment by Zawadidone** [comment] 2021-06-22 14:55
Yes it is thanks

**Closed** 2021-06-22 14:55 UTC
Labels: enhancement
