### ISSUE TITLE
[Bug] Some prebuilt rules match source events in `elastic-cloud-logs-*`

### ISSUE THREAD

**Issue by banderror** [elastic/detection-rules#3225] opened 2023-10-25 10:00 UTC
FYI: this bug is SDH-linked.

## Summary

One user reported that the [Cobalt Strike Command and Control Beacon](https://www.elastic.co/guide/en/security/current/cobalt-strike-command-and-control-beacon.html) rule generates alerts based on source events from the `elastic-cloud-logs-*` index in their ESS environment.

This rule has only the following index patterns that don't match `elastic-cloud-logs-*`: [`packetbeat-*`, `auditbeat-*`, `filebeat-*`, `logs-network_traffic.*`]. Despite that, it looks like somehow in ESS Cloud `logs-network_traffic.*` or `filebeat-*` index patterns match concrete indices of `elastic-cloud-logs-*`, presumably via aliases. Specifically, in the user's environment they see alerts generated from source events from indices like this one:

```json
 "signal.ancestors.index": [
      ".ds-elastic-cloud-logs-8-2023.10.17-000376"
    ],
```

## Suggestion

In Security UI, when users create a custom rule, by default we explicitly exclude `elastic-cloud-logs-*` indices by adding `-*elastic-cloud-logs-*` to the list of index patterns:

<img width="976" alt="Screenshot 2023-10-24 at 19 13 06" src="https://github.com/elastic/detection-rules/assets/7359339/fa22eb17-ca3b-4b22-a404-fbe57a47aef0">

Probably we should add `-*elastic-cloud-logs-*` to:

- either just all our prebuilt rules
- or to prebuilt rules having any index patterns containing `logs-` or `filebeat-`?

**Comment by SHolzhauer** [comment] 2023-11-27 16:31
I believe `logs-*` somehow points to the `elastic-loud-logs`, have seen same behavior in our cluster and excluding it did fix it.

**Comment by w0rk3r** [comment] 2023-12-05 17:57
@banderror, I'm closing this issue as resolved. The bug, which seems to be an edge case, only affected one rule (confirmed by telemetry) was made possible due to a syntax error in a Lucene query (This query type is used in 5 rules, and that will be reduced to 1 after https://github.com/elastic/detection-rules/pull/3194 merges) fixed in https://github.com/elastic/detection-rules/pull/3196. Let me know if you want to discuss it further.

Related Internal [Slack thread](https://elastic.slack.com/archives/C03DXS9UZDF/p1698228563684409)

**Closed by w0rk3r** 2023-12-05 17:57 UTC
Labels: bug, discuss

**Comment by w0rk3r** [comment] 2023-12-07 14:41
Hey @banderror, Sounds like a Lucene/detection engine bug to me.

IMO, we don't need to exclude explicitly because this rule was the only occurrence across all of our rules (900+) and was caused by a syntax bug in a language that we are not using but replacing.

It may not be the best approach too. If it didn't respect the indexes defined in the first place, it could ignore the exclusion too. Perhaps we should open an issue to investigate the root cause that made the rule query other indices than specified. Wdyt?

**Comment by banderror** [comment] 2023-12-07 15:40
> If it didn't respect the indexes defined in the first place, it could ignore the exclusion too. Perhaps we should open an issue to investigate the root cause that made the rule query other indices than specified. Wdyt?

@w0rk3r That's a good point 👍 I agree that knowing what's happening is important to make informed decisions about fixes. I'll bring this up to our tech leads and see what they think about investigating what might be the exact reason. Thank you for your feedback.
