### ISSUE TITLE
[Bug] issue workflow mislabeled

### ISSUE THREAD

**Issue by brokensound77** [elastic/detection-rules#2616] opened 2023-03-05 19:19 UTC
**Describe the bug**
in #2615 it was [labeled](https://github.com/elastic/detection-rules/actions/runs/4337518494/jobs/7573573976) as `community` even though it was created by an Elastician. This is the first occurrence I have noticed of this.

This could also just have been a one off error, which will add the label

```
} catch (error) {
    return "notMember";
  }
```

**Comment by Mikaayenson** [comment] 2023-03-05 19:39
The issue is that when I recently recreated the token, I did not add the scope to read organization team members. I just added the scope and tested by creating a couple fake issues.

GH Action before token modification: https://github.com/elastic/detection-rules/actions/runs/4337668357
GH Action after adding org member read scope to token: https://github.com/elastic/detection-rules/actions/runs/4337674965

With the update, this should be fixed.

**Closed by Mikaayenson** 2023-03-05 19:39 UTC
Labels: bug, community
